name: eshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_dotenv: ^5.0.2
  get_storage: ^2.0.3
  flutter_launcher_icons: ^0.11.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  flutter_spinkit: ^5.1.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path: assets/applauncher.png
  ios: true

flutter: 
  assets:
    - assets/images/
    - assets/icons/
    - assets/.env
    - assets/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/Lobster-Regular.ttf
    - family: Libre_Baskerville
      fonts:
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Regular.ttf
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Italic.ttf
        - asset: assets/fonts/Libre_Baskerville/LibreBaskerville-Bold.ttf
  uses-material-design: true


